### ISSUE TITLE
反编译扫描不到jar包和class文件

### ISSUE THREAD

**Issue by st-lucifer** [SpringKill-team/SecurityInspector#10]
文件中有jar包相关
![image](https://github.com/user-attachments/assets/d4e2b5d4-a20e-46b8-8372-c60c572b8175)
但是插件读不到
![image](https://github.com/user-attachments/assets/eeb02d61-a573-4ff0-9f8f-8134dd9dc7b7)

**Comment by springkill** [comment]
你好，可以从action中下载临时推送的软件包，这个是老版本的一个bug,目前已经修复。

**Comment by springkill** [comment]
#7

**Comment by springkill** [comment]
最新版本已发布，可前往release下载
