### ISSUE TITLE
集成依赖nbvcxz库

### ISSUE THREAD

**Issue by C1heck0ut** [SpringKill-team/SecurityInspector#2]
在使用 SecurityInspector 时报错 java.lang.NoClassDefFoundError: me/gosimple/nbvcxz/Nbvcxz，貌似插件依赖于 nbvcxz 库中的 Nbvcxz 类，但该类并未包含在插件中，可否打包添加到插件中呢

**Comment by springkill** [comment]
你好，已经收到反馈，我们将尽快发布新版本
