### ISSUE TITLE
Decompiler功能bug

### ISSUE THREAD

**Issue by g7shot** [SpringKill-team/SecurityInspector#4]
师傅师傅，idea最新版本Decompiler窗口不显示加载的jar包，maven导入的jar貌似也不行。

**Comment by springkill** [comment]
你好，收到反馈，我在测试的时候也有这个问题，应该会有报错，能不能提供下报错信息

**Comment by g7shot** [comment]
2024-10-28 09:36:08,528 [  16442]   INFO - STDOUT - pom.xml does not exist 
2024-10-28 09:36:08,528 [  16442]   INFO - STDOUT - JAR files in lib directory: [] 
2024-10-28 09:36:08,528 [  16442]   INFO - STDOUT - Maven JAR files: []
没报错，翻日志只有这个

**Comment by springkill** [comment]
收到反馈，方便发一下你检查的项目的目录结构吗，看起来像是没有正确识别到pom.xml文件

**Comment by springkill** [comment]
> 2024-10-28 09:36:08,528 [ 16442] INFO - STDOUT - pom.xml does not exist 2024-10-28 09:36:08,528 [ 16442] INFO - STDOUT - JAR files in lib directory: [] 2024-10-28 09:36:08,528 [ 16442] INFO - STDOUT - Maven JAR files: [] 没报错，翻日志只有这个

收到反馈，方便发一下你检查的项目的目录结构吗，看起来像是没有正确识别到pom.xml文件

**Comment by g7shot** [comment]
> > 2024-10-28 09:36:08,528 [ 16442] INFO - STDOUT - pom.xml does not exist 2024-10-28 09:36:08,528 [ 16442] INFO - STDOUT - JAR files in lib directory: [] 2024-10-28 09:36:08,528 [ 16442] INFO - STDOUT - Maven JAR files: [] 没报错，翻日志只有这个
> 
> 收到反馈，方便发一下你检查的项目的目录结构吗，看起来像是没有正确识别到pom.xml文件

这个日志是我测试的本地的一个项目，maven项目和一般java项目(手动导入jar包)我都测试了没有显示，maven项目我用的是https://github.com/chillzhuang/SpringBlade，作者可以试试？

**Comment by g7shot** [comment]
是支持maven嘛

**Comment by springkill** [comment]
> 是支持maven嘛

是支持maven的，不过现在功能写的很简单，我查看了你给出的项目，很符合实际应用时候的复杂场景，我们将尝试使用你给出的项目进行maven解析优化，感谢支持

**Comment by g7shot** [comment]
> > 是否支持maven呢
> 
> 是支持maven的，不过现在功能写的很简单，我查看了你给出的项目，很符合实际应用时的复杂场景，我们将尝试使用你给出的项目进行maven解析优化，谢谢支持

口误我是想说只支持maven嘛，那种手动导入的jar批量反编译这个功能个人感觉很实用。期待ing

**Comment by springkill** [comment]
> > > 是否支持maven呢
> > 
> > 
> > 是支持maven的，不过现在功能写的很简单，我查看了你给出的项目，很符合实际应用时的复杂场景，我们将尝试使用你给出的项目进行maven解析优化，谢谢支持
> 
> 口误我是想说只支持maven嘛，那种手动导入的jar批量反编译这个功能个人感觉很实用。期待ing

手动导入的jar包现在是自动识别项目下的lib目录
反编译功能后续会增强，现在的功能确实很弱，感谢你的关注，我们将尽快更新

**Comment by springkill** [comment]
已增强Decompiler功能
