### ISSUE TITLE
注入检测问题

### ISSUE THREAD

**Issue by Best-XC** [SpringKill-team/SecurityInspector#6]
SQL注入检测太弱，很多项目有注入无法检测

**Comment by springkill** [comment]
收到反馈，能否提供下具体检测不到的方法名称和类名称，感谢

**Comment by Best-XC** [comment]
> 收到反馈，能否提供下具体检测不到的方法名称和类名称，感谢
目前来看只能识别jdbc的“+”的sql注入问题，无法识别到mybatis的$

**Comment by springkill** [comment]
> > 收到反馈，能否提供下具体检测不到的方法名称和类名称，感谢
> > 目前来看只能识别jdbc的“+”的sql注入问题，无法识别到mybatis的$

收到回复，我们已解决你提到的问题，将和sql注入的其他新功能一起提交，届时会在此issue下回复，感谢你的建议和支持。
